### ISSUE TITLE
Не заводи лишних переменных

### ISSUE THREAD

**Issue by Red-Cat-Fat** [negrime/3DClicker#6]
А зачем заводил _shootingTrigger?
https://github.com/negrime/3DClicker/blob/c44b3a10a012432a96c741c14620d4ca02dc69d6/3DClicker/Assets/Scripts/CommonSoldier.cs#L87

**Comment by negrime** [comment]
Исправил

**Comment by Red-Cat-Fat** [comment]
Ссылку на комит пожалуйста дай

**Comment by negrime** [comment]
https://github.com/negrime/3DClicker/commit/17379154a8ed899ff92706b183b8c859e6384fa4
